### ISSUE TITLE
possible bug in fit_cylinder

### ISSUE THREAD

**Issue by yfly99** [SKrisanski/FSCT#14]
I might be wrong but I think this line should be
line_centre = np.mean([np.min(group[:, :3], axis=0), np.max(group[:, :3], axis=0)], axis=0) 

https://github.com/SKrisanski/FSCT/blob/8dcec7600c2aeafd63e3bccbdfa3a19aa5a580fb/scripts/measure.py#L609

**Comment by SKrisanski** [comment]
Hi,
You are indeed correct! Good catch. Fixing that likely will improve the accuracy/reliability. I've just pushed a fix.
Thanks for pointing it out.
Sean
