### ISSUE TITLE
good initial cylinders but tree not included

### ISSUE THREAD

**Issue by Rotoslider** [SKrisanski/FSCT#16]
See attached image. I was wondering what might cause a tree to not be included in the list when has really good initial cylinders and full cyl.array but the but the cleaned and interpolated for that tree is missing. 
![non included tree](https://user-images.githubusercontent.com/15005663/172511214-491466d5-d6c6-4681-a72e-ea8f23281756.jpg)

**Comment by SKrisanski** [comment]
Hmmm, that's an interesting one. Is this with default settings? Would you mind sending me the stem_points and the full_cyl_array? If you're willing, the input point cloud might also be helpful for working out what is going on. Thanks!

**Comment by Rotoslider** [comment]
The only thing not default is sort_stems is 0. 
I am uploading the files now to my Gdrive. Once I get a link I will send it. 2.6gb for the input cloud. gonna take a while here. Slow internet.

**Comment by Rotoslider** [comment]
https://drive.google.com/drive/folders/1pz6tAcxmchrWAQBPLe5L5TkRmPtD8Si4

**Comment by SKrisanski** [comment]
Sorry for the slow reply. I've processed your point cloud from scratch using defaults, and I'm not seeing the same behaviour. That said, I'm having trouble finding the above location in the point cloud, so I could be missing it. Do you have the coordinates of the tree you show above in the point cloud so I can see if I'm getting the same behaviour? Also, would you mind adding all of the visualised cylinders and the text_point_cloud you generated to that drive?
Thanks,
Sean

**Comment by Rotoslider** [comment]
Sean,
Thank you for checking it out. I have since built a new computer to run this on and have run it again. I do not have any missing trees in the new run. Same data set just different results. Which is to be expected I would assume. 
I unfortunately do not have the results with the original issue anymore.

**Comment by SKrisanski** [comment]
Glad to hear it worked! Strange that it didn't get all trees previously if it didn't crash. No problem about the data, as that's only to find the problem if it persisted.
