### ISSUE TITLE
Out of memory Does it use Swap file on Windows

### ISSUE THREAD

**Issue by Rotoslider** [SKrisanski/FSCT#17]
numpy.core._exceptions._ArrayMemoryError: Unable to allocate 33.0 GiB for an array with shape (276460629, 16) and data type int64

My Windows pc is rather old and only have 32gb of ram. I have a dedicated SSD for the swap file with the size set to 60gb. I seem to have run outta memory.  Does FSCT use the Page file when it runs outta ram?

**Comment by SKrisanski** [comment]
Yes it does use the page file. If you use a large enough point cloud though, memory usage can get pretty extreme. For a while I had my page file set to 500GB for when 128GB of RAM was not enough...

Generally, it will be better to split up the point cloud rather than make use of the page file, but that does have some inconveniences associated with it. Eventually, I'll add the tiling features to address this.

**Comment by Rotoslider** [comment]
Thanks

**Comment by Rotoslider** [comment]
I have since built a better computer to run this on. Its a i9 running 18 cores at 4.6ghz,  I have 128gb ram and a 1tb m2 drive for the swap file. I only set it to 500gb and ran outta memory after it thought for 3 days on the file. Next time I will set it to use the full terabyte for the swap.
The point cloud is 17gb and a bit over 700 million points. It took 3 days to do the preprocessing. I assume it finished thee preprocessing and died on the next numpy step. See below. 
Is there a way to start from there with a bigger swap and nt have to rerun the processing again? There are 19142 npy files in the working directory.
[out of memory 169gb.txt](https://github.com/SKrisanski/FSCT/files/8953562/out.of.memory.169gb.txt)

**Comment by SKrisanski** [comment]
Great to hear. You can indeed skip preprocessing. Just set preprocess=0 in run.py (note: this just requires that the preprocessing has been run already, and the samples generated by preprocessing are in the working directory).
The same concept applies for the other steps too. I.e. you can rerun just the "measure" part if you have the outputs from the prior steps.
When you run it, just select the input point cloud exactly how you would do it normally if you were running from the start.

**Comment by Rotoslider** [comment]
I know this is closed but I thought you might want to see this out of memory error. Its a bit extreme for the data set.
`FSCT\lib\site-packages\numpy\linalg\linalg.py", line 1648, in svd
    u, s, vh = gufunc(a, signature=signature, extobj=extobj)
numpy.core._exceptions._ArrayMemoryError: Unable to allocate 8.26 TiB for an array with shape (1065702, 1065702) and data type float64`
I assume that's 8 terabytes. 
The file was a small section of a road scan. A total of 173 trees and points were around 6 million. Working Las file size is 401.462KB
I was testing a slam file I made while driving down a road.

**Comment by SKrisanski** [comment]
Hmmm that's an interesting one!
Would you mind sending me the dataset so I can see if I can replicate it? I wouldn't be able to look immediately, but it's an interesting one to add to the list.
What are the dimensions of the dataset? Is it sparse but a relatively large area?

**Comment by Rotoslider** [comment]
Yes its a sparse but largish area.  I sent to a link to the file.
