### ISSUE TITLE
Change clasess

### ISSUE THREAD

**Issue by shorzov** [SKrisanski/FSCT#19]
Hello!

Thank you so much for your efforts on this project. This is amazing!

I'd like to know how I can change the list of classes for segmentation. Instead of "terrain," I'd want to see "ground" as a class. I'd also like to include "standing deadwood," "lying deadwood," and "crowns."

I'm running your script with data from the Borreal Forest, so the classes must be changed for my requirements.

Thank you very much!

**Comment by SKrisanski** [comment]
Hi Shorzov.

Glad to hear you like it!
So the class names can be changed if you simply rename all mentions of the 4 classes throughout all of the FSCT code. As long as you are careful to be consistent, you shouldn't break anything.
FSCT outputs these classes under the "label" category in the output .las files. You can change this too, again just be consistent throughout the code if you do so and it shouldn't break.
FSCT doesn't have functionality to detect dead trees currently, and does not directly output the tree crowns. It would be possible to add this functionality, and I would be open to adding this to the idea list, but I can't promise when I would get to it (might be a month, might be a year). I would suggest considering the crown to be the vegetation points assigned to a particular tree. If that definition works for your goals, you could add some code to extract it just after the vegetation assignment when it's looping through all of the individual trees.
The upper branches can be tricky to map well enough for FSCT to detect them as part of the stem class, as the tops of trees move a lot more during scanning, are generally smaller, so your relative errors are much larger, and beam divergence effects get worse if scanning from the ground.

Hopefully that helps.
All the best,
Sean
