### ISSUE TITLE
Errors after interpolated_full_cyl_array.las

### ISSUE THREAD

**Issue by gistin** [SKrisanski/FSCT#2]
Hi,

It seems that the temporary file "interpolated_full_cyl_array.las" is not saved and it errors with "FileNotFoundError: [Errno 2] No such file or directory:" 

Thanks

**Comment by SKrisanski** [comment]
Hi Gistin, 
Thanks for letting me know. Should be fixed now. Seems I accidentally uploaded a version of measure.py that I was using for testing.
Cheers,
Sean
