### ISSUE TITLE
How to fine tune the parameters of FSCT?

### ISSUE THREAD

**Issue by ShukhratSh** [SKrisanski/FSCT#22]
Dear Sean Krisanski,
Thank you so much for your effort to create a tree segmentation tool from point cloud data sets. I set up the package successfully and ran it on the testing data set that you have provided. However, the results achieved are far from what I was expecting. I was wondering if you have a look and let me know if I am doing something wrong or missing something. Basically, I run "run.py" and selected an "example.las" file in the "test" data set after installing the package on a server. I haven't changed any other script. As I used provided test dataset with a code I expected better results.
Results are as follows:

1. Vegetation_points.las
![image](https://user-images.githubusercontent.com/11915606/188224501-868341ac-6223-4800-b155-399d8e4449dc.png)

As you see vegetation points include coarse woody debris and stems but misses most of the tree canopy.

2. veg_points_sorted.las
![image](https://user-images.githubusercontent.com/11915606/188224919-9bb87662-6e15-4924-8244-f202a3f2433b.png)

Sorted vegetation points miss most of the vegetation.

3.  tree_aware_cropped_point_cloud.las
![image](https://user-images.githubusercontent.com/11915606/188225238-d92deb8c-a81b-4d75-b71a-487fc457d8d3.png)

4. terrain_points.las
![image](https://user-images.githubusercontent.com/11915606/188225466-d76202b2-2ead-4136-8d50-9a0d3032973c.png)
Looks good.

5.  stem_points_sorted.las
![image](https://user-images.githubusercontent.com/11915606/188227428-7c6bf15b-d966-4eb6-a818-3d64f44850cf.png)

stem points looks good, but still not great comparing to following original test data:
![image](https://user-images.githubusercontent.com/11915606/188227638-af509813-15a4-4e8d-ae5a-81073527f850.png)

6.  skeleton_visualisation.las
![image](https://user-images.githubusercontent.com/11915606/188227854-49b88614-f441-42b4-a01b-70d7c80f5159.png)

7. segmented_cleaned.las 

![image](https://user-images.githubusercontent.com/11915606/188228019-bfcd6545-e614-4c39-ad03-e6c6203db8c2.png)
It looks like this is just original data colored by height.

8. initial_cyl_viz.las
![image](https://user-images.githubusercontent.com/11915606/188228364-7b04e8b5-44c1-43bc-bf52-2deda1efd7e4.png)
As you can see initial cylinders don't look great.

9.  ground_veg.las
![image](https://user-images.githubusercontent.com/11915606/188228751-9bda8c6d-cf9d-4d49-a13a-fbbd4d2f1e7f.png)

As you see ground vegetation also includes stems probably <1.3m

10. cwd_points.las
![image](https://user-images.githubusercontent.com/11915606/188228945-88f40384-4d7e-452a-965c-f28e0fed0fda.png)
It is not capturing CWD.

11. cleaned_cylinders.las
![image](https://user-images.githubusercontent.com/11915606/188229109-20343ffa-af28-4f65-8715-9b880a871e70.png)

Cleaned cylinders look good, but the upper parts of trees are missing.

12. I also run your script on small part of my TLS data and results don't look good (segmented.las - left, original point cloud - right) 
![image](https://user-images.githubusercontent.com/11915606/188254483-ccfb1133-bc10-43ea-bb69-b3a48ccfa911.png)

Despite it produced some point cloud, at some point it returned following error:
`Making full_cyl visualisation...
Traceback (most recent call last):
  File "run.py", line 54, in <module>
    FSCT(
  File "/gpfs/data1/vclgp/shokirovs/FSCT/scripts/run_tools.py", line 44, in FSCT
    measure1.run_measurement_extraction()
  File "/gpfs/data1/vclgp/shokirovs/FSCT/scripts/measure.py", line 930, in run_measurement_extraction
    initial_cyl_vis = np.vstack(initial_cyl_vis)
  File "<__array_function__ internals>", line 180, in vstack
  File "/home/shokirovs/.local/lib/python3.8/site-packages/numpy/core/shape_base.py", line 282, in vstack
    return _nx.concatenate(arrs, 0)
  File "<__array_function__ internals>", line 180, in concatenate
ValueError: need at least one array to concatenate
`

My question is, am I doing something wrong when I run the code. Can I fine tune the model parameters to achieve better results? If yes, can you please give me some instructions?

Thank you very mich and I'm looking forward to your help.

**Comment by SKrisanski** [comment]
Hi ShukhratSh.
I have occasionally seen some unusual variation in the segmentation using different devices. CPU sometimes gives worse segmentation than GPU, but I think this is more of a PyTorch quirk than FSCT. I'm not certain, but it seems like there is a bit of performance variation with different PyTorch versions/devices.

The segmentation looks considerably poorer than it should be. I just ran it myself and got much nicer looking results than above. My ground_veg.las didn't have any stems. You can see where stems would be from the text_point_cloud.las shown here too.
![image](https://user-images.githubusercontent.com/16696855/189134867-88facf1d-3d1b-4879-84e9-b2777c6b77eb.png)

Unfortunately, I don't have much helpful advice for the segmentation, other than trying on another machine or using GPU if you were using CPU.

It's hard to be sure from the image, but that TLS looks quite low resolution. If it is a bit too low resolution, that would cause problems for FSCT's segmentation. By TLS, are you referring to the high-accuracy/resolution tripod mounted variety or something else?

A few visualisation tips:
- In the Scalar Fields section in CloudCompare, try changing the "Active" field. In some of those point clouds where there will be several scalar fields. One of them is height above DTM, but you will also find fields like "label" which is the segmentation label, "tree_id", etc.
- Eye Dome Lighting is awesome and makes everything much easier to see. The button is second from the top on the right hand toolbar.
![image](https://user-images.githubusercontent.com/16696855/189133218-3132c5bc-76a8-4fa0-9819-55026167f69a.png)

Hopefully you manage to get it working better on your machine! Sorry I couldn't be of much help with this one.
All the best,
Sean

**Comment by ShukhratSh** [comment]
Dear Sean Krisanski,

Thank you very much for your time and quick response. I used a CPU as I was having a problem with running a GPU. I didn't expect that outputs would vary depending on CPU/GPU. I will try to run the script with the GPU then. I installed FSCT and all the dependencies in requirements.txt. I thought the same PyTorch version installed as the one you are using, what version of PyTorch do you suggest installing?

I collected 7 TLS scans (yes, Topcon GLS 2000 on tripod) in 1 ha plot as I had many plots to scan, and the landscape is Australian woodland. My point cloud is sparse and quite occluded. It might be the reason for poor segmentation. I will try to run the code with dense point clouds.

Thank you,
Shukhrat

**Comment by ShukhratSh** [comment]
OK, finally, I run the code with GPU and segmentation result is much better than the CPU.
Thank you a lot for your help,
Shukhrat

**Comment by SKrisanski** [comment]
Glad I could help! 
I'll add a note to the README about CPU vs GPU. I don't know why it performs so differently on CPU vs GPU.
All the best,
Sean
