### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by emanthi** [SKrisanski/FSCT#3]
![Screenshot_1](https://user-images.githubusercontent.com/98092891/150328660-541214f5-566c-4c15-bfc6-7d226743e9fd.png)
 Im getting this error everytime after preprocessing. Someone know how to fix this?

**Comment by SKrisanski** [comment]
Hi emanthi,
This is a path error as a result of it not finding the model.pth file. I've fixed a bug in the code which should hopefully fix it for you. The bug wasn't an issue on my Windows or Ubuntu systems (so I missed it), but was still not meant to be there.
Could you please try cloning again and rerunning or just replacing the "other_parameters.py" file with the new one?
Could you also confirm whether or not that fix worked for you?
Cheers,
Sean

**Comment by emanthi** [comment]
Hello,
Now, doenst reach pre processing anymore, getting this error in any pointclound i try:
[error.txt](https://github.com/SKrisanski/FSCT/files/7907196/error.txt)
And i increased even more the page file to 150mb

**Comment by SKrisanski** [comment]
Would you be able to share your error in a different way? The more info you can give me, the better I can help. Currently, I can't access your file. The change should not have affected preprocessing at all, only the path to the segmentation model file used in "inference.py"

**Comment by emanthi** [comment]
Ho, i download the whole files again and forgot to change it i think. i ll try tomorrow, had no time till today, i ll give feedback later

**Comment by SKrisanski** [comment]
Would you be able to try running from inside the scripts directory? It uses relative paths (../model/model.pth), so it matters where you run the code from. It goes up one directory (..) then down into the model directory (/model/) to find the model file (model.pth).
I will fix it with a more general solution in the future, but hopefully that works for you. If that fails, you could just edit the code to put an absolute path to the "model.pth" file. Hopefully that fixes the issue for you. 

I'll leave the issue open until I replace the relative paths with something better.

**Comment by emanthi** [comment]
![Screenshot_2](https://user-images.githubusercontent.com/98092891/151268449-67d3b0ba-1767-4196-b2ed-fea20cbe8bfd.png)
Now is running smoother, but got this error after tree aware cropped point cloud. Seems like some code error, you got anything like this before?

**Comment by SKrisanski** [comment]
Glad to see it's working on your end now other than that bug. I've just fixed the bug in measure.py if you want to download the latest version. It didn't show up during my testing as it happens in a bit of an edge case. You may want to try increasing the `tree_base_cutoff_height` as FSCT has rejected the cylinders in one of the cylinder/tree sorting steps. It may have rejected them if the data was not quite right for FSCT's requirements. If you have issues with it still, are you able to take some screenshots of stem_points.las with Eye Dome Lighting on in CloudCompare? What type of data is it? TLS, ALS, photogrammetry, etc.?

**Comment by emanthi** [comment]
Just missing the "text_point_cloud.las" that was the file that i wanted to analyze on cloud compare . It's photogrammetry cloud done in pix4d. The stem_points.las is not very good and i disabled it in the previous version because i dont need it, forgot to disable this time. ill download the new files and test again, to see if can get the text_point_cloud file

**Comment by SKrisanski** [comment]
Hi Emanthi. If the stem_points.las isn't very good, the rest of FSCT won't work properly. With photogrammetry, the datasets do need to be of very high quality and completeness or the segmentation will perform poorly -> leading to the rest of FSCT not working properly. The 2 photogrammetry datasets in my FSCT video give an idea of the quality required. The text_point_cloud file will not be generated if no stems were detected/successfully measured (there are no measurements to visualise in a text_point_cloud in such a situation). Fortunately, it sounds like you're all sorted on the code aspects for now. I recommend trying FSCT on a TLS dataset or similar to start with to get familiar with how it works (it's fairly reliable on most TLS datasets) and then branching out to more difficult/lower quality datasets to understand what the limitations of the tool are. All the best!
