### ISSUE TITLE
Numpy and hdbscan incompatibility

### ISSUE THREAD

**Issue by xiangtaoxu** [SKrisanski/FSCT#5]
Hi, I was testing FSCT today and I got the following error after following the instructions.

`numpy.ndarray size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject`

After some search, I believe it is because the incompatibility of the hdbscan package and the numpy package. After running `pip install --upgrade numpy`, which upgrade numpy from 1.20 to 1.22. The problem resolves.

Thought this would be helpful for other people

**Comment by xiangtaoxu** [comment]
Also cudatoolkit needs to be included in the requirements.txt if GPU is to be used

**Comment by SKrisanski** [comment]
Hi xiangtaoxu. Thanks for letting me know. I'm fixing up the requirements now.

**Comment by ylevental** [comment]
Just commenting that I also received this error.

**Comment by SKrisanski** [comment]
Thanks Andrew, always happy to see it getting used. This issue should be resolved now, as I've just updated the requirements.txt file. Closing this issue for now, but feel free to reopen it or make another one if you have any further troubles. Cheers!
