### ISSUE TITLE
Better clarification needed in "training a new semantic segmentation model" - Step 2

### ISSUE THREAD

**Issue by ylevental** [SKrisanski/FSCT#7]
The /sample_dir/ folders don't exist, so you should instruct the user to create these folders

**Comment by SKrisanski** [comment]
Hi. Please see section "Step 3 - Preprocessing the training data" for usage. There is a simple boolean you set to either 1 (or True) or 0 (False). There is a boolean for train, validation and test. This boolean should be true on the first run with a new training dataset. The code will automatically create the necessary sample directories and create the 6x6x6m cube shaped point cloud slices (the samples) from the labeled point cloud/s you place in the respective train, validation, and test directories.

The reason you change these booleans back to 0 after the first run is to stop it deleting the existing sample_dirs and preprocessing the data again. You can also use these booleans one at a time: i.e. if you changed the contents of the train folder but not the test folder, you don't need to reprocess the test folder.
Please note: training your own model for FSCT should be considered advanced usage of the tool. If making your own datasets, please read my semantic segmentation paper, which explains the rationale of why I labeled the data the way I did. If you deviate from this (intentionally or not), the assumptions that FSCT relies upon will probably break, so be prepared to go deep into studying and modifying the code.
You can also leverage FSCT to mostly make the training data for you. It can't magically learn to beat it's limitations, but careful, iterative use of well-segmented and/or manually corrected segmented_cleaned.las files is quite powerful. The train script applies a lot of carefully thought out augmentation automatically. I have another model coming to the repo (when I find time), that has been trained from scratch this way on data I did not manually label at all, with very promising results.

**Comment by ylevental** [comment]
@SKrisanski Hello, thanks for replying to me.  I did set all the booleans to 1, but I could not find in the code where the sample directories are created.  Usually, this is done with os.mkdir().  Could you show me where the sample directories are supposed to be created?  Thanks.

I'm doing a research project, so this should be rather advanced.

**Comment by ylevental** [comment]
Closing, I re-posted in the latest thread.
